# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'autor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'carroceria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'consorcio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fabricante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('linha', models.CharField(max_length=10)),
                ('ordem', models.CharField(blank=True, max_length=10, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('fonte', models.CharField(blank=True, max_length=200)),
                ('dataInclusao', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busdata.Autor')),
                ('carroceria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busdata.Carroceria')),
                ('consorcio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busdata.Consorcio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdata.Empresa')),
            ],
            options={
                'db_table': 'registro',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carroceria',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdata.Fabricante'),
        ),
    ]
