# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consorcio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('linha', models.CharField(max_length=10)),
                ('ordem', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=200)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdata.Consorcio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busdata.Empresa')),
            ],
            options={
                'db_table': 'registro',
                'managed': True,
            },
        ),
    ]
