# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ordem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
