# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdata', '0002_auto_20170325_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='cor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
